services:
  - type: web
    name: wiki-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python wiki_chatbot.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /
    autoDeploy: false